[build]
  command = "CI=false npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  BROWSERSLIST_IGNORE_OLD_DATA = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200